parameters:
- name: NpmPublish
  displayName: 'NPM packages publish configuration'
  type: string
  values:
  - 'nightly (@dev)'
  - 'release candidate (@rc)'
  - 'production (@latest)'
  - 'custom'
  default: 'nightly (@dev)'

variables:
  ${{ if eq(parameters.NpmPublish, 'nightly (@dev)') }}:
    npm_packaging_mode: 'dev'
  ${{ if eq(parameters.NpmPublish, 'release candidate (@rc)') }}:
    npm_packaging_mode: 'rc'
  ${{ if eq(parameters.NpmPublish, 'production (@latest)') }}:
    npm_packaging_mode: 'release'
  ${{ if eq(parameters.NpmPublish, 'custom') }}:
    npm_packaging_mode: '$(VersionSuffix)'

jobs:
- template: templates/react-native-ci.yml
  parameters:
    NpmPackagingMode: ${{ variables.npm_packaging_mode }}
    IsReleasePipeline: false
    BuildConfig: 'Release'
    PoolName: 'Linux-CPU-2019'
